### ISSUE TITLE
Add Knative build controller

### ISSUE THREAD

**Issue by iamsubratp** [GoogleCloudPlatform/oss-test-infra#108]
What would you like to be added:
Add knative build controller to oss-test-infra prow instance.
Why is this needed:
We want to use knative build step functionality

**Comment by BenTheElder** [comment]
@cjwagner @fejta is this currently usable? what does this entail?

**Comment by iamsubratp** [comment]
@cjwagner can you please respond to this?

**Comment by cjwagner** [comment]
Sounds like we are going to get rid of the knative build controller because it is deprecated (https://github.com/kubernetes/test-infra/issues/14626) and Guest OS is going to make their postsubmit jobs handle the git tagging itself. We hope to better support these kinds of use cases in the future with proper Prow+Tekton integration.

**Comment by iamsubratp** [comment]
since knative builds are going to be deprecated; and we decided to take a different approach for this problem, closing this issue
